// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@mui/core";
import * as Styles from "@mui/styles";
import * as Colors from "@mui/core/colors";

var useStyles = Styles.makeStyles({
      fontSize: {
        fontSize: "30px"
      },
      bgColor: {
        backgroundColor: Colors.red[300]
      }
    });

function ExampleClassOverride(Props) {
  var classes = useStyles();
  return React.createElement(Core.Button, {
              children: "Example Button",
              classes: {
                root: classes.fontSize,
                containedPrimary: classes.bgColor
              },
              color: "primary",
              variant: "contained"
            });
}

var make = ExampleClassOverride;

export {
  useStyles ,
  make ,
  
}
/* useStyles Not a pure module */
